### PR TITLE
fix: fix correctly convert enum values (#17, #19)

### LINKED ISSUE #17: Directories marked for deletion inside cloneIDLs may not exist
Affects "clean" environments. 

https://github.com/jodinathan/js_bindings/blob/f73540b4b245402e063d50c6bc851344576ec32f/tool/crawler/build.dart#L120

### LINKED ISSUE #19: Enum getters/setter don't translate correctly
Take the `RequestCache` enum:

```dart
enum RequestCache {
  valueDefault,
  noStore,
  reload,
  noCache,
  forceCache,
  onlyIfCached
}
```

When used, for example on a `Request`, the following getter is called:

```dart
RequestCache get cache =>
      RequestCache.values.byName(js_util.getProperty(this, 'cache'));
```

Properties on the API are not camel-cased, therefore `only-if-cached` won't match an enum property.

When being used as a setter, `name` is used:

```dart
  set cache(RequestCache newValue) {
    js_util.setProperty(this, 'cache', newValue.name);
  }
```

So the underlying context would get `onlyIfCached` rather than `only-if-cached` (for example).

### PR DESCRIPTION
**Pull request by Ehesp**
Fixes https://github.com/jodinathan/js_bindings/issues/17
Fixes https://github.com/jodinathan/js_bindings/issues/19

Broken into 3 commits:

1. [Fix crawler](https://github.com/jodinathan/js_bindings/commit/265406e0475cd4ec943a44977a85e8694f2515fb) - some parts were commented out or didn't check for Directory existence, assuming this was pushed up whilst testing.
2. [Add enum values](https://github.com/jodinathan/js_bindings/commit/331173654521e63fbfbf3e744f453ca28c9f8e65) - attaches the raw values to the enum, adds a static method to the enum, and then updates the build to convert between these.
3. [Regen build](https://github.com/jodinathan/js_bindings/commit/79568d8bef4b43e7a6e64385391526a2b49611ec) - regen the build, includes the enum fix + other things which have been pulled in.
4. [Fix iterable enums](https://github.com/jodinathan/js_bindings/pull/20/commits/2adf35596d8a71f21252e6f98c76325361af2e8d) - iterable enums were using `.names` which is still incorrect, so this commit fixes it to convert the iterable to a iterable containing the `value` instead of the name.

### CODE REVIEW

**Review by jodinathan — COMMENTED** [review]
Can you please edit the CHANGELOG and add info for the stuff you fixed in a 0.0.8 log item?

**Comment by Ehesp** [comment]
Sure, will sort in a couple of hours 👍

**Comment by Ehesp** [comment]
@jodinathan done

**Review by jodinathan — APPROVED** [review]
thanks

**Pull request merged**
